server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
    cache: false
    check-template: true
    enabled: true
    prefix: classpath:/static/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  devtools:
    enabled: true
    additional-paths: src/main/java

  # 数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useCompression=true&useServerPrepStmts=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

  # jpa的相关配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true

  # redis的相关配置
  redis:
    hostName: 192.168.163.128
    port: 6379
    # redis 密码
    password: 123
    # 客户端超时时间单位是毫秒 默认是2000
    timeout: 5000
    # 最大空闲数
    maxIdle: 20
    # 连接池的最大数据库连接数
    maxActive: -1
    # 控制一个pool可分配多少个jedis实例,用来替换上面的maxActive
    maxTotal: 100
    # 最大建立连接等待时间。如果超过此时间将接到异常
    maxWaitMillis: 100
    # 连接的最小空闲时间
    minEvictableIdleTimeMillis: 864000000
    # 每次释放连接的最大数目
    numTestsPerEvictionRun: 10
    # 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程
    timeBetweenEvictionRunsMillis: 300000
    # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    # 在空闲时检查有效性
    testWhileIdle: false
    # 数据库
    database: 0

# mybatis的相关配置
mybatis:
  type-aliases-package: com.demo.model
  mapperLocations: classpath*:mapper/*/*.xml